export const productList = [
  {
    id: 1,
    images: [
      { source: require('../assets/images/product-01.jpg') },
      { source: require('../assets/images/product-02.jpg') },
      { source: require('../assets/images/product-03.jpg') },
    ],
    name: 'Gucci Wear',
    price: 300,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 234,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 2,
    images: [
      { source: require('../assets/images/product-03.jpg') },
      { source: require('../assets/images/product-04.jpg') },
      { source: require('../assets/images/product-05.jpg') },
    ],
    name: 'Fendi Wear',
    price: 570,
    discounted: true,
    discountPrice: 482,
    colors: [{ name: 'teal' }, { name: 'grey' }, { name: 'lemon' }],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Bottomwear',
    category: 'women',
    wishedBy: 89,
    wished: true,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'Jeans',
    itemsSold: 139,
  },
  {
    id: 3,
    images: [
      { source: require('../assets/images/product-05.jpg') },
      { source: require('../assets/images/product-06.jpg') },
      { source: require('../assets/images/product-07.jpg') },
    ],
    name: 'Puma Kit',
    price: 3000,
    discounted: false,
    discountPrice: undefined,
    colors: [{ name: 'red' }, { name: 'orange' }, { name: 'black' }],
    brand: 'Puma',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Sportwear',
    category: 'Kid',
    wishedBy: 201,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'Men Sportwear',
    itemsSold: 382,
  },
  {
    id: 4,
    images: [
      { source: require('../assets/images/product-06.jpg') },
      { source: require('../assets/images/product-07.jpg') },
      { source: require('../assets/images/product-08.jpg') },
    ],
    name: 'Channel Blazers',
    price: 2330,
    discounted: true,
    discountPrice: 2100,
    colors: [{ name: 'peach' }, { name: 'cyan' }, { name: 'maroon' }],
    brand: 'Channel',
    sex: 'Female',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 201,
    wished: true,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'Blazzers',
    itemsSold: 532,
  },
  {
    id: 5,
    images: [
      { source: require('../assets/images/product-08.jpg') },
      { source: require('../assets/images/product-09.jpg') },
      { source: require('../assets/images/product-10.jpg') },
    ],
    name: 'Gucci Wear',
    price: 300,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 6,
    images: [
      { source: require('../assets/images/product-01.jpg') },
      { source: require('../assets/images/product-12.jpg') },
      { source: require('../assets/images/product-13.jpg') },
    ],
    name: 'Emporio Armani Overall',
    price: 3200,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Female',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Kids',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 7,
    images: [
      { source: require('../assets/images/product-13.jpg') },
      { source: require('../assets/images/product-14.jpg') },
      { source: require('../assets/images/product-15.jpg') },
    ],
    name: 'Gucci Wear',
    price: 300,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 8,
    images: [
      { source: require('../assets/images/product-15.jpg') },
      { source: require('../assets/images/product-16.jpg') },
      { source: require('../assets/images/product-05.jpg') },
    ],
    name: 'Balenciaga Wear',
    price: 3300,
    discounted: true,
    discountPrice: 3240,
    colors: [
      { name: 'royalblue' },
      { name: 'purple' },
      { name: 'violet' },
      { name: 'gray' },
    ],
    brand: 'Balenciaga',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
    ],
    type: 'Watch',
    category: 'Men',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 9,
    images: [
      { source: require('../assets/images/product-01.jpg') },
      { source: require('../assets/images/product-02.jpg') },
      { source: require('../assets/images/product-03.jpg') },
    ],
    name: 'Gucci Wear',
    price: 300,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
  {
    id: 10,
    images: [
      { source: require('../assets/images/product-01.jpg') },
      { source: require('../assets/images/product-02.jpg') },
      { source: require('../assets/images/product-03.jpg') },
    ],
    name: 'Gucci Wear',
    price: 300,
    discounted: false,
    discountPrice: undefined,
    colors: [
      { name: 'red' },
      { name: 'blue' },
      { name: 'pink' },
      { name: 'lemon' },
    ],
    brand: 'Gucci',
    sex: 'Male',
    sizes: [
      { name: 'Small', slug: 'S' },
      { name: 'Medium', slug: 'M' },
      { name: 'Extra-Large', slug: 'XL' },
      { name: '3-Extra-Large', slug: '3XL' },
    ],
    type: 'Topwear',
    category: 'Men',
    wishedBy: 2,
    wished: false,
    carted: false,
    ordered: false,
    orderInfo: {
      quantity: undefined,
      color: undefined,
      size: undefined,
    },
    tag: 'T Shirt',
    itemsSold: undefined,
  },
];
