export const menWearCategory = [
  { name: 'Topwear' },
  { name: 'Bottomwear' },
  { name: 'Underwear' },
  { name: 'Sportwear' },
  { name: 'Festivalwear' },
  { name: 'Plus size' },
  { name: 'Watches' },
  { name: 'Bags/Shoes' },
];

export const topWearType = [
  { name: 'T-shirts', slug: 'tShirts' },
  { name: 'Casual shirts', slug: 'casualShirts' },
  { name: 'Formal shirts', slug: 'formalShirts' },
  { name: 'Sweat shirts', slug: 'sweatShirts' },
  { name: 'Jackets', slug: 'jackets' },
  { name: 'Hoodies', slug: 'hoodies' },
  { name: 'Sweaters', slug: 'sweaters' },
];

export const wearBrand = [
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 1,
    name: 'Adidas',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 2,
    name: 'American Eagle',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 3,
    name: 'Armani Exchange',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 4,
    name: 'Balenciaga',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 5,
    name: 'Billabong',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 6,
    name: 'Burberry',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 7,
    name: 'CAT',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 8,
    name: 'Calvin Klein',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 9,
    name: 'Channel',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 10,
    name: 'Chloe',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 11,
    name: 'Columbia',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 12,
    name: 'Denim',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 13,
    name: 'Diesel',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 14,
    name: 'Dolce & Gabbana',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 15,
    name: 'Dsquared2',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 16,
    name: 'EastLand',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 16,
    name: 'Emporio Armani',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 17,
    name: 'Eleventy',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 18,
    name: 'Fendi',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 19,
    name: 'Fila',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 20,
    name: 'Giorgo Armani',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 21,
    name: 'G-Star',
  },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 22,
    name: 'Guiseppe Zanotti',
  },
  { name: 'Gucci' },
  {
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 23,
    name: 'Hamilton',
  },
  // { name: 'Hermes' },
  // { name: 'HUGO BOSS' },
  // { name: 'Iceberg' },
  // { name: 'Jack & Jones' },
  // { name: 'Jordan' },
  // { name: 'Karl Lagerfeld' },
  // { name: 'Kangol' },
  // { name: 'Katty Perryl' },
  // { name: 'Kendall + Kylie' },
  // { name: 'Keneth Cole' },
  // { name: 'Kenzo' },
  // { name: "La'Blanca" },
  // { name: 'Lacoste' },
  // { name: 'Lee' },
  // { name: "Levi's" },
  // { name: 'Louis Vuitton' },
  // { name: 'Micheal Kors' },
  // { name: 'Mulberry' },
  // { name: 'No21' },
  // { name: 'Nautica' },
  // { name: 'New Balance' },
  // { name: 'Nike' },
  // { name: "O'Neill" },
  // { name: 'Oakley' },
  // { name: 'Oasis' },
  // { name: 'Off-white' },
  // { name: 'Paul Smith' },
  // { name: 'Perry Ellis' },
  // { name: 'Philip Plein' },
  // { name: 'Polo Ralph Lauren' },
  // { name: 'Prada' },
  // { name: 'Puma' },
  // { name: 'Ralph Lauren' },
  // { name: 'Saint Lauren' },
  // { name: 'Timberland' },
  // { name: 'Tom Ford' },
  // { name: 'Tommy Hilfiger' },
  // { name: 'Toms' },
  // { name: 'Trademark' },
  // { name: 'U.S. Polo' },
  // { name: 'Umbro' },
  // { name: 'Undercover' },
  // { name: 'Versace' },
  // { name: 'Versace Jeans' },
  // { name: 'Victoria Beckham' },
  // { name: 'Vogue' },
  // { name: 'Wardrobe.NYC' },
  // { name: 'Xander Zhou' },
  // { name: 'Xiao Wang' },
  // { name: 'Xu Zhi' },
  // { name: 'Yeezy' },
  // { name: 'Yvonne Leon' },
  // { name: 'Zack' },
  // { name: 'Zents' },
  // { name: 'Zuomba' },
  // { name: 'Zuo' },
];

export const wearColor = [
  // { name: 'RED' },
  {
    name: 'ORANGE',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 1,
  },
  // { name: 'YELLOW' },
  // { name: 'GREEN' },
  // { name: 'BLUE' },
  // { name: 'BLACK' },
  {
    name: 'INDIGO',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 2,
  },
  {
    name: 'VIOLET',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 3,
  },
  {
    name: 'PURPLE',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 4,
  },
  // { name: 'WHITE' },
  // { name: 'GRAY' },
  {
    name: 'PINK',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 5,
  },
  {
    name: 'BLUE',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 6,
  },
  {
    name: 'RED',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 7,
  },
  {
    name: 'BLACK',
    isSelected: false,
    selectedClass: { name: 'square-o', color: '#fff' },
    id: 8,
  },
];

export const wearSize = [
  // { name: 'XXXS' },
  // { name: 'XXS' },
  // { name: 'XS' },
  { name: 'S' },
  { name: 'M' },
  { name: 'L' },
  { name: 'XL' },
  { name: 'XXL' },
  { name: '3XL' },
];

export const wearFilterCategory = [
  { name: 'Brand' },
  { name: 'Color' },
  { name: 'Size' },
  { name: 'Price' },
  { name: 'Offer' },
];

export const filterLetter = [
  { name: '#' },
  { name: 'A' },
  { name: 'B' },
  { name: 'C' },
  { name: 'D' },
  { name: 'E' },
  { name: 'F' },
  { name: 'G' },
  { name: 'H' },
  { name: 'I' },
  { name: 'J' },
  { name: 'K' },
  { name: 'L' },
  { name: 'M' },
  { name: 'N' },
  { name: 'O' },
  { name: 'P' },
  { name: 'Q' },
  { name: 'R' },
  { name: 'S' },
  { name: 'T' },
  { name: 'U' },
  { name: 'V' },
  { name: 'W' },
  { name: 'X' },
  { name: 'Y' },
  { name: 'X' },
  { name: 'Z' },
];
